### ISSUE TITLE
Applying a GtkTextTag to a GtxTextBuffer doesn't work

### ISSUE THREAD

**Issue by vixalien** [ahgilak/deno_gi#1]
only relevant code showed for brevity. full code available on request

```ts
// text buffer
const buffer = new Gtk.TextBuffer();

// creation of tag
const bold_tag = Gtk.TextTag.new("bold");
bold_tag.weight = Pango.Weight.BOLD;
buffer.tagTable.add(this.tag_bold);

// actual bolding
app_action.connect("activate", () => {
	const [selected, start, end] = text_view.buffer.getSelectionBounds();
      buffer.applyTagByName(
        "bold",
        start,
        end,
      );
})
```

Error:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
    parameters.push(ffiType(argTypeTag));
               ^
    at createCallback (file:///home/alien/sites/deno_gi/src/types/callback.ts:64:16)
    at JSToGIInterface (file:///home/alien/sites/deno_gi/src/types/argument.ts:301:14)
    at JSToGIArgument (file:///home/alien/sites/deno_gi/src/types/argument.ts:194:29)
    at file:///home/alien/sites/deno_gi/src/types/callable.ts:86:38
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (file:///home/alien/sites/deno_gi/src/types/callable.ts:82:16)
    at file:///home/alien/sites/gnotes/win.ts:78:10
    at file:///home/alien/sites/deno_gi/src/types/callback.ts:72:25
    at invoke (file:///home/alien/sites/deno_gi/src/types/callable.ts:209:20)
    at file:///home/alien/sites/deno_gi/src/types/callable.ts:99:23
```

I was messing around the code and it turns out the `parameter` variable is `undefined`. I tried initialising it to an empty array but deno crashes.

**Comment by ahgilak** [comment]
@vixalien
Just saw the notifications and it looks like you've been quite active on the project.
Thank you. It is really encouraging to see such support.
I'll check the issues and PRs ASAP.

meanwhile, could you check if ![this issue](#1) is still there relevant? I think it is fixed by now.

**Comment by vixalien** [comment]
@ahgilak, thanks, it's an honor. I made those PRs to try to solve issues I encountered while working with deno_gi, some may not be the best solutions and I'm welcome to discuss them.

Also note that I wrote the PRs late at night so I apologise for the code and commit messages 😅

**Comment by vixalien** [comment]
I think this issue is fixed, even though I didn't get to check that. Closing.
