### ISSUE TITLE
Floats are not working

### ISSUE THREAD

**Issue by vixalien** [ahgilak/deno_gi#29]
Hello!

There is a problem that is very interesting and I couldn't solve it.

When setting a float value, the value is set as an integer instead. For example:

```ts
import { require } from "./mod.ts"

const Gdk = require("Gdk", "4.0");

const color = new Gdk.RGBA();
color.red = 0.4;
console.log("red", color.red); // 1053609165
```

**Comment by ahgilak** [comment]
Hello.

I thinks it's not about floats, It's rather about struct fields.
Can you test a float property in a GObject?

Also output of the above code is 0 when i run it.

**Comment by vixalien** [comment]
Yes you're right. I found out that there's a regression with struct fields. I have had a local fix for ages and will push it soon™.

The real issue in my opinion is that there's way too many bugs we introduce with each PR that are small to notice and they get worse over time. That's why I will be focusing on writing tests in #14. I will resume work only when there will be (almost) complete coverage.

This is also recommended by Gobject-introspection as per https://gi.readthedocs.io/en/latest/writingbindings/guidelines.html

> Use the Everything library in your unittests, aim at testing all functions there. Do testing as early as possible in the development of the binding, as the code is likely to be more complex than you anticipate.

**Comment by ahgilak** [comment]
This looks partially fixed but floats are not completely consistent yet
This is the output of the sample code using the latest version:
```
red 0.4000000059604645
```

**Comment by vixalien** [comment]
Hello, yes this is the behaviour of javascript.

The same behavior is exhibited in GJS

```
gjs> const color = new imports.gi.Gdk.RGBA();
gjs> color.red
0
gjs> color.red = 0.4
0.4
gjs> color.red
0.4000000059604645
```
