### ISSUE TITLE
Use `connect` instead of `on`

### ISSUE THREAD

**Issue by vixalien** [ahgilak/deno_gi#4]
Hello. Very lovely project!

I think it would be better if the project recommended the use of `connect` and `disconnect` instead of the archaic node-style `on` and `off`. This would make it more consistent with GObject signals and how they are handled in GJS.

**Comment by ahgilak** [comment]
I added `disconnect` method so both styles are supported now, but I'm not sure if GJS style would be preferred way, since naming conversions are derived from node-gtk.

**Comment by vixalien** [comment]
Thanks. I see.

I come from GJS so I am quite familiar to it's style.

Maybe you can consider about using the GJS style instead, as it is already quite similar to how other bindings work and there is no need to learn new patterns for people already familiar with Gtk.

The first concern is the use of `on` and `off` for signals, which reminds me of the old node `EventEmitter` which is really not found anywhere. As I mentioned  `connect` and `disconnect` will feel more familiar to other Gtk users. And it's nice to have a consistent style.

Secondly, I wonder why properties and methods are in camelCase instead of snake_case, which is also more familiar in Gtk (eg `gtk_widget_init_template`)

**Comment by ahgilak** [comment]
Hello. Yes.
Since we're now using `vfunc_` before virtual functions, it's kinda mix of node and gjs styles.
I agree with completely switching to gjs style (signals, name conversions and everything else)

**Comment by ahgilak** [comment]
Also It's good to keep `on`, `once` and `off` methods as alternatives.
Just replace them in the examples.

**Comment by ahgilak** [comment]
thank you in advance
